// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scpnwbsynrxnqlcvwnln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjcG53YnN5bnJ4bnFsY3Z3bmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzU5ODUsImV4cCI6MjA2MzQxMTk4NX0.cm06fopj1yp_M4V9K79ZUCl-sk-nHs9dGLz-r_jZ7fA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);